### ISSUE TITLE
ImportError: cannot import name 'TOTAL_MEMORY' from 'distributed.worker'

### ISSUE THREAD

**Issue by ericdill** [rapidsai/dask-cuda#161]
Importing LocalCudaCluster fails with this stack trace:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-99db4c1b1421> in <module>
      1 import cudf
----> 2 from dask_cuda import LocalCUDACluster

~/miniconda/envs/rapidsai/lib/python3.7/site-packages/dask_cuda/__init__.py in <module>
----> 1 from .local_cuda_cluster import LocalCUDACluster
      2 from .dgx import DGX
      3 
      4 from ._version import get_versions
      5 __version__ = get_versions()['version']

~/miniconda/envs/rapidsai/lib/python3.7/site-packages/dask_cuda/local_cuda_cluster.py in <module>
      5 from dask.distributed import LocalCluster
      6 from distributed.utils import parse_bytes
----> 7 from distributed.worker import TOTAL_MEMORY
      8 
      9 from .device_host_file import DeviceHostFile

ImportError: cannot import name 'TOTAL_MEMORY' from 'distributed.worker' (/home/ericdill/miniconda/envs/rapidsai/lib/python3.7/site-packages/distributed/worker.py)
```

environment.yml:
```
name: rapidsai
channels:
  - rapidsai
  - nvidia
  - numba
  - conda-forge
  - defaults
dependencies:
  - cudf=0.9
  - cuml=0.9
  - cugraph=0.9
  - python=3.7
  - cudatoolkit=10.0
  - dask-cuda
  - pip
```

Full env:
```
conda list -n rapidsai
# packages in environment at /home/ericdill/miniconda/envs/rapidsai:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
aiohttp                   3.6.2                    pypi_0    pypi
arrow-cpp                 0.14.1           py37h5ac5442_4    conda-forge
async-timeout             3.0.1                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                    pypi_0    pypi
bokeh                     1.3.4                    pypi_0    pypi
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.7             he1b5a44_1000    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.13.0           py37h8022711_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_0    conda-forge
cudatoolkit               10.0.130                      0    nvidia
cudf                      0.9.0                    py37_0    rapidsai
cugraph                   0.9.0                    py37_0    rapidsai
cuml                      0.9.1           cuda10.0_py37_0    rapidsai
cython                    0.29.13          py37he1b5a44_0    conda-forge
cytoolz                   0.10.0           py37h516909a_0    conda-forge
dask-core                 2.6.0                      py_0    conda-forge
dask-cuda                 0.9.1                    py37_0    rapidsai
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.6.0                    pypi_0    pypi
distributed               2.6.0                      py_0    conda-forge
dlpack                    0.2                  he1b5a44_1    conda-forge
double-conversion         3.1.5                he1b5a44_1    conda-forge
entrypoints               0.3                      pypi_0    pypi
fastavro                  0.22.5           py37h516909a_0    conda-forge
gflags                    2.2.2             he1b5a44_1001    conda-forge
glog                      0.4.0                he1b5a44_1    conda-forge
grpc-cpp                  1.23.0               h18db393_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                      pypi_0    pypi
importlib-metadata        0.23                     pypi_0    pypi
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.3                   pypi_0    pypi
jsonschema                3.1.1                    pypi_0    pypi
jupyter-server-proxy      1.1.0                    pypi_0    pypi
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
jupyterlab-nvdashboard    0.1.11                   pypi_0    pypi
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcudf                   0.9.0                cuda10.0_0    rapidsai
libcugraph                0.9.0                cuda10.0_0    rapidsai
libcuml                   0.9.1                cuda10.0_0    rapidsai
libcumlprims              0.9.0                cuda10.0_0    nvidia
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnvstrings              0.9.0                cuda10.0_0    rapidsai
libopenblas               0.3.7                h6e990d7_2    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.9.0                cuda10.0_0    rapidsai
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.30.0           py37hf484d3e_0    numba
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
more-itertools            7.2.0                    pypi_0    pypi
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
multidict                 4.5.2                    pypi_0    pypi
nbconvert                 5.6.0                    pypi_0    pypi
nbformat                  4.4.0                    pypi_0    pypi
nccl                      2.4.6.1              cuda10.0_0    nvidia
ncurses                   6.1               hf484d3e_1002    conda-forge
notebook                  6.0.1                    pypi_0    pypi
numba                     0.46.0          np116py37hf484d3e_0    numba
numpy                     1.16.4           py37h95a1406_0    conda-forge
nvstrings                 0.9.0                    py37_0    rapidsai
openssl                   1.1.1c               h516909a_0    conda-forge
packaging                 19.2                     pypi_0    pypi
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
pandocfilters             1.4.2                    pypi_0    pypi
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.5.1                      py_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.2.0                    pypi_0    pypi
pip                       19.3                     py37_0    conda-forge
prometheus-client         0.7.1                    pypi_0    pypi
prompt_toolkit            2.0.10                     py_0    conda-forge
psutil                    5.6.3            py37h516909a_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pyarrow                   0.14.1           py37h8b68381_2    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pynvml                    8.0.3                    pypi_0    pypi
pyparsing                 2.4.2                    pypi_0    pypi
pyrsistent                0.15.4                   pypi_0    pypi
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py37h516909a_0    conda-forge
pyzmq                     18.1.0           py37h1768529_0    conda-forge
re2                       2019.09.01           he1b5a44_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
rmm                       0.9.0                    py37_0    rapidsai
send2trash                1.5.0                    pypi_0    pypi
setuptools                41.4.0                   py37_0    conda-forge
simpervisor               0.3                      pypi_0    pypi
six                       1.12.0                py37_1000    conda-forge
snappy                    1.1.7             he1b5a44_1002    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
terminado                 0.8.2                    pypi_0    pypi
testpath                  0.4.2                    pypi_0    pypi
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
uriparser                 0.9.3                he1b5a44_1    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
yarl                      1.3.0                    pypi_0    pypi
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      0.6.0                    pypi_0    pypi
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

Seems like we need a new conda package of dask-cuda 0.9 that has an upper-bound of distributed compatibility until there's a new release of dask-cuda (0.10 or 0.11) that works with the newest distributed. As of now it's not clear to the end user what version of distributed needs to be pinned without digging pretty deep into the stack. 

If you pin your conda env definition to using dask=2.3 and distributed=2.3 then importing LocalCUDACluster works, but there's another error in the distributed.nanny when you try and create a LocalCUDACluster():
```
distributed.nanny - WARNING - Restarting worker
distributed.nanny - ERROR - Failed to restart worker after its process exited
Traceback (most recent call last):
  File "/home/ericdill/miniconda/envs/rapidsai/lib/python3.7/site-packages/distributed/nanny.py", line 382, in _on_exit
    await self.instantiate()
  File "/home/ericdill/miniconda/envs/rapidsai/lib/python3.7/site-packages/distributed/nanny.py", line 321, in instantiate
    result = await self.process.start()
  File "/home/ericdill/miniconda/envs/rapidsai/lib/python3.7/site-packages/distributed/nanny.py", line 492, in start
    msg = await self._wait_until_connected(uid)
  File "/home/ericdill/miniconda/envs/rapidsai/lib/python3.7/site-packages/distributed/nanny.py", line 593, in _wait_until_connected
    msg = self.init_result_q.get_nowait()
  File "/home/ericdill/miniconda/envs/rapidsai/lib/python3.7/multiprocessing/queues.py", line 126, in get_nowait
    return self.get(False)
  File "/home/ericdill/miniconda/envs/rapidsai/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
TypeError: new() takes 1 positional argument but 2 were given
```

Let me try the nightly build and see if that works.

**Comment by pentschev** [comment]
dask-cuda 0.10 is out on the `rapidsai` conda channel now. I will tentatively close this as the new version should fix it, but feel free to reopen in case you see this still.

**Comment by ranaalisaeed** [comment]
This issue still exists with the latest versions below:

distributed       2.25.0
dask              2.25.0
dask-cuda         0.9.1
dask-cudf         0.15.0

Please suggest a solution.

**Comment by pentschev** [comment]
@ranaalisaeed according to your comment, you're still on dask-cuda 0.9.1, please try upgrading it to 0.15.
