### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address with XGB.dask

### ISSUE THREAD

**Issue by IzzyPutterman** [rapidsai/dask-cuda#814]
When running inside a docker container using dask-cuda and xgb.dask, I get the following error OSError: [Errno 99] Cannot assign requested address.

Here is my LocalCUDACluster:
LocalCUDACluster(
        interface='eth0',
        protocol='ucx,
        CUDA_VISIBLE_DEVICES=visible_devices,
        rmm_pool_size=get_rmm_size(device_pool_size),
        local_directory=dask_space,
        device_memory_limit=0.8,
        enable_tcp_over_ucx=True,
        enable_nvlink=True)

Here is my error message:
File "/workspace/inference/downstream.py", line 232, in run_downstream
    model = xgb.dask.train(client=client, 
  File "/opt/conda/lib/python3.8/site-packages/xgboost/dask.py", line 964, in train
    return client.sync(_train_async, global_config=config.get_config(), **args)
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 861, in sync
    return sync(
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 326, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 309, in f
    result[0] = yield future
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/conda/lib/python3.8/site-packages/xgboost/dask.py", line 831, in _train_async
    _rabit_args = await _get_rabit_args(len(workers), client)
  File "/opt/conda/lib/python3.8/site-packages/xgboost/dask.py", line 789, in _get_rabit_args
    env = await client.run_on_scheduler(_start_tracker, n_workers)
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 2427, in _run_on_scheduler
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.8/site-packages/xgboost/dask.py", line 130, in _start_tracker
    rabit_context = RabitTracker(hostIP=host, nslave=n_workers)
  File "/opt/conda/lib/python3.8/site-packages/xgboost/tracker.py", line 171, in __init__
    sock.bind((hostIP, _port))
OSError: [Errno 99] Cannot assign requested address

Package version: 
dask: 2021.7.1
xgboost: 1.4.2

**Comment by pentschev** [comment]
@IzzyPutterman from what I've seen in other conversations, this seems like may have been resolved, could you confirm? Are we good to close this?

**Comment by IzzyPutterman** [comment]
@pentschev I just ran with the 21.12 pytorch image, the error still occurs.  From the old thread I don't think there was a resolution, just that it had happened before but no fix.

**Comment by pentschev** [comment]
Just to be clear, you're saying the `OSError: [Errno 99] Cannot assign requested address` error still happens, or are you seeing an error that's different from that?

**Comment by IzzyPutterman** [comment]
Exact same error message and log as above.

**Comment by IzzyPutterman** [comment]
`[2022-01-06 17:19:36,721][numba.cuda.cudadrv.driver][INFO] - init
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.worker - WARNING - Run Failed
Function: _start_tracker
args:     (1)
kwargs:   {}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 4102, in run
    result = function(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/xgboost/dask.py", line 130, in _start_tracker
    rabit_context = RabitTracker(hostIP=host, nslave=n_workers)
  File "/opt/conda/lib/python3.8/site-packages/xgboost/tracker.py", line 171, in __init__
    sock.bind((hostIP, _port))
OSError: [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/workspace/xgboost.py", line 16, in fit
    model = xgb.dask.train(client=client, params=self.config, dtrain=dtrain, 400, evals=[(dtrain, 'train')])
  File "/opt/conda/lib/python3.8/site-packages/xgboost/dask.py", line 964, in train
    return client.sync(_train_async, global_config=config.get_config(), **args)
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 860, in sync
    return sync(
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 326, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 309, in f
    result[0] = yield future
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/conda/lib/python3.8/site-packages/xgboost/dask.py", line 831, in _train_async
    _rabit_args = await _get_rabit_args(len(workers), client)
  File "/opt/conda/lib/python3.8/site-packages/xgboost/dask.py", line 789, in _get_rabit_args
    env = await client.run_on_scheduler(_start_tracker, n_workers)
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 2373, in _run_on_scheduler
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.8/site-packages/xgboost/dask.py", line 130, in _start_tracker
    rabit_context = RabitTracker(hostIP=host, nslave=n_workers)
  File "/opt/conda/lib/python3.8/site-packages/xgboost/tracker.py", line 171, in __init__
    sock.bind((hostIP, _port))
OSError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launch.py", line 17, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 237, in run_and_report
    assert mdl is not None
AssertionError
Exception ignored in: <function RabitTracker.__del__ at 0x7f81ee787790>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/xgboost/tracker.py", line 188, in __del__
    self.sock.close()
AttributeError: 'RabitTracker' object has no attribute 'sock'
`

**Comment by pentschev** [comment]
@IzzyPutterman just for completeness, have you by any chance tried xgboost 1.5.1 with this too?

**Comment by pentschev** [comment]
@trivialfis I confirmed with @IzzyPutterman he tried 1.5.1 as well, but this seems like xgboost getting the incorrect hostname/IP address in https://github.com/dmlc/xgboost/blob/91c1a1c52f3ad7b33caae159abf2bd7b006be97c/python-package/xgboost/dask.py#L142-L143 , but it's a problem on NGC only, do you have any ideas what could be the problem there and potential solutions?

**Comment by kevingerman** [comment]
It seems like XGBoost is getting the correct IP for the default interface in that container.  

```
$ hostname -i
0.38.106.236
```

However, when tracker.py tries to bind a socket explicitly to that interface it gets that vague OS Error 99.  
My *guess* is that it is a permissions issue having to do with the fabric used to provision the network on which NGC runs the containers for our jobs.

Simple reproduction of the error ...

```
$ python
>>> import socket
>>> sock=socket.socket(  socket.getaddrinfo( '0.38.106.236', None)[0][0], socket.SOCK_STEAM)
>>> sock.bind(('0.38.106.236', 9999))  #<--- raises OS Error 99 on NGC nodes
>>> sock.bind(('0.0.0.0', 9999)) #<--- succeeds and binds the socket to all available interfaces
```

This might point out another with XGBoost and multinode jobs.  XGBoost will need ports between 9901 and 9999 open for RabitTracker to listen on.

**Comment by kevingerman** [comment]
Seems like there are 2 thiings going on.   NGC appears to have a configuration issue which causes containers to come up with the default interface uninitialized.  My guess, Kubernetes CNI black magic.

The other issue is that XGBoost has a partial fix for this on the JVM side of things with, [#3833](https://github.com/dmlc/xgboost/pull/3833) but nothing on the python or R side. A comparable solution is needed for the python side of things, or better yet a general solution with comparable behavior in all supported runtimes.

**Comment by trivialfis** [comment]
Hi, I opened a PR for specifying the IP address of the scheduler, feel free to test it ;-)

https://github.com/dmlc/xgboost/pull/7581

**Comment by trivialfis** [comment]
https://github.com/dmlc/xgboost/pull/7581 is merged.  I think we can close this now. ;-)

**Comment by IzzyPutterman** [comment]
Pushed container with updated xgboost to NGC and reran the jobs that previously failed.  Seems like this specific error no longer occurs, thank you!

**Comment by Amoshen** [comment]
I think your ip in LocalCUDACluster is totally different with that in hostIP gotten by "rabit_context = RabitTracker(hostIP=host, nslave=n_workers)". My ip in LocalCUDACluster is 127.0.0.1, so I assign 127.0.0.1 for host at "rabit_context = RabitTracker(hostIP=host, nslave=n_workers)".
